stages:
  - test
  - deploy

services:
  - name: docker:dind
    command: ["--insecure-registry=local-registry:5000"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

test:
  stage: test
  image: python:3.6-slim
  before_script:
  - pip install virtualenv --quiet
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  script:
    - pip install tox --quiet
    - tox -e py36

deploy:
  stage: deploy
  script:
    - docker build --pull -t local-registry:5000/devops-challenge .
    - docker push local-registry:5000/devops-challenge